title: "Pingstkyrkan i Åmål"
description: ""
url: "https://pingstamal.se"
lang: sv
author: ""
theme: minima
markdown: kramdown
minima:
  skin: classic

header_pages:
  - vad-vi-goer.md
  - vad-vi-tror-pa.md
